### ISSUE TITLE
Impossible to press Alt+~

### ISSUE THREAD

**Issue by magiblot** [TragicWarrior/vwm#18]
Hello,
In my keyboard distribution (`es_ES`) the character `~` requires the combination `AltGr+4` or `AltGr+ñ`. Thus, `Alt+AltGr+4` won't open the Main Menu (`Alt+~`).
What can I do?
Thanks.

**Comment by magiblot** [comment]
Oh, well, I figured out it works by pressing the combination Alt+` twice. However, it's not trivial to guess.

**Comment by TragicWarrior** [comment]
@magiblot , take a look at the example vwmrc config file.  you can find it in the samples directory.  you will also find a directory called keycodes and a simple program inside.  it will give you the keystroke value for the key combination that you press.  just put the value into the config file.

**Comment by magiblot** [comment]
Thanks @TragicWarrior for the fast reply.

**Comment by TragicWarrior** [comment]
@magiblot , you should not have to press [alt + ~] twice.  try the setting up a new hotkey using the info i shared with you.

**Comment by magiblot** [comment]
In our language we often write ` or ´ over certain letters. So, in the Spanish keyboard distribution, à is written [a + `] and the standalone ` character is written [` + `]. That's why.

**Comment by TragicWarrior** [comment]
@magiblot , did setting a new hotkey solve the problem for you?

**Comment by magiblot** [comment]
Hello again, thanks for the interest. Actually, I didn't try changing the hotkey setting as I stopped using vwm, but it would have probably worked.

So we can consider this issue solved.

Cheers.
